apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-header
spec:
  headers:
    customRequestHeaders:
      Host: "minio.default.svc.cluster.local:9000"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  # No namespace defined
spec:
  stripPrefix:
    prefixes:
      - /minio
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.middlewares: default-test-header@kubernetescrd,default-strip-prefix@kubernetescrd

spec:
  rules:
  - http:
      paths:
      - path: '/'
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9090
      - path: '/minio'
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000            
      - path: '/backend'
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: '/frontend'
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80        
      