apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-compose
  labels:
    app: worker-compose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-compose
  template:
    metadata:
      labels:
        app: worker-compose
    spec:
      containers:
      - name: worker-compose
        image: ghcr.io/ikkyusan193/p2-test/worker:latest
        imagePullPolicy: Always
        env:
        - name: MINIO-ACCESS-KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: minio-access-key
        - name: MINIO-SECRET-KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: minio-secret-key
        - name: MINIO-HOST
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: minio-host
        - name: REDIS-HOST
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: redis-host
        - name: REDIS-PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: redis-port             
        - name: REDIS-ROOT-PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: redis-root-password
        - name: LISTEN-QUEUE
          value: Compose
      imagePullSecrets:
      - name: dockerconfigjson-secret